### PR TITLE
Throw a proper exception instead of complaining about invalid JSON on…

### PR DESCRIPTION
**Pull request by elestedt**
… authentication failure

### CODE REVIEW

**Comment by jonas0007** [comment]
Can you fix the build please? Seams like a reference is missing.

**Comment by elestedt** [comment]
I will. I also have a couple of more fixes coming. So I'll get it all sorted asap.

**Comment by elestedt** [comment]
There. Finally :)

**Comment by jonas0007** [comment]
Thanks!

**Comment by elestedt** [comment]
When do you think that you'll make a release to nuget with these fixes?

**Comment by jonas0007** [comment]
The automatic nuget file creation was broken. Fixed it and a new package is on its way.

**Comment by elestedt** [comment]
Thanks :-)

**Pull request merged**
