### PR TITLE
Added refresh worklogs method on Issue

### PR DESCRIPTION
**Pull request by amitla**

### CODE REVIEW

**Comment by jonas0007** [comment]
Can you please explain the changes you have made to the web.config file please? If there is no good reason, please undo these changes.

**Comment by amitla** [comment]
hi,

I didn't find any changes made to web.config. can you point me to the relevant commit?

**Comment by jonas0007** [comment]
Yes, I did mean the csproj. Sorry for the confusion :).

**Comment by amitla** [comment]
hi, 
That's OK. :) If I remember correctly it had to do with the build - your CI didn't build correctly until I marked the references not to depend on a specific version.

**Comment by jonas0007** [comment]
Ok, fine for me, maybe they changed something in the AppVeyor configs...

**Pull request merged**
